sudo: false
cache: pip
language: python
python: 3.6

env:
    - TOX_ENV=py35-django22
    - TOX_ENV=py36-django22
    - TOX_ENV=py37-django22
    - TOX_ENV=py37-django30
    - TOX_ENV=py37-django31
    - TOX_ENV=py38-django22
    - TOX_ENV=py38-django30
    - TOX_ENV=py38-django31
    - TOX_ENV=py39-django22
    - TOX_ENV=py39-django30
    - TOX_ENV=py39-django31
    - TOX_ENV=flake8
    - TOX_ENV=docs
    - TOX_ENV=coveralls

install:
    - pip install tox

script:
    - tox -e $TOX_ENV
