on:
  workflow_call:
    inputs:
      pyver:
        required: true
        type: string

jobs:
  tox:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "PYVER=${{ inputs.pyver }}" >> $GITHUB_ENV
          echo pyver: ${{ inputs.pyver }}
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ inputs.pyver }}
          cache: 'pip'
      - run: python -m pip install --upgrade tox
