# Generated by Django 4.0.8 on 2023-01-25 23:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DateHierarchyModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='SluggedField',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Spam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('a', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ACollectionOfSpamAndEggsAndOtherStuff',
            fields=[
                ('spam_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='test_app.spam')),
                ('this_should_be_something_really_long_a', models.CharField(max_length=100)),
                ('this_should_be_something_really_long_b', models.CharField(max_length=100)),
                ('this_should_be_something_really_long_c', models.CharField(max_length=100)),
                ('this_should_be_something_really_long_d', models.CharField(max_length=100)),
            ],
            bases=('test_app.spam',),
        ),
        migrations.CreateModel(
            name='Eggs',
            fields=[
                ('spam_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='test_app.spam')),
                ('b', models.CharField(max_length=100)),
            ],
            bases=('test_app.spam',),
        ),
    ]
