# Generated by Django 6.0.6 on 2026-06-18 22:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Author",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(help_text="search_fields.", max_length=100)),
                (
                    "slug",
                    models.SlugField(
                        help_text="prepopulated from name.", max_length=100
                    ),
                ),
                (
                    "bio",
                    models.TextField(
                        blank=True, help_text="TextField: skipped by list_filter."
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Appears in list_display and drives search_fields.",
                        max_length=100,
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        help_text="Auto-prepopulated from name in the generated admin.",
                        max_length=100,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "categories",
            },
        ),
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(help_text="Drives search_fields.", max_length=50),
                ),
                ("slug", models.SlugField(help_text="Auto-prepopulated from name.")),
            ],
        ),
        migrations.CreateModel(
            name="Post",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(help_text="list_display.", max_length=200)),
                (
                    "slug",
                    models.SlugField(
                        help_text="prepopulated from title.", max_length=200
                    ),
                ),
                (
                    "body",
                    models.TextField(help_text="TextField: skipped by list_filter."),
                ),
                (
                    "created_at",
                    models.DateField(
                        help_text="DateField named 'created_at': becomes date_hierarchy."
                    ),
                ),
                (
                    "published_at",
                    models.DateField(
                        help_text="DateField: list_filter (not date_hierarchy by name)."
                    ),
                ),
                (
                    "is_published",
                    models.BooleanField(
                        default=False, help_text="BooleanField: list_filter."
                    ),
                ),
                (
                    "author",
                    models.ForeignKey(
                        help_text="FK with few rows: becomes a list_filter.",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="blog.author",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        help_text="FK with few rows: becomes a list_filter.",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="blog.category",
                    ),
                ),
                (
                    "tags",
                    models.ManyToManyField(
                        help_text="M2M: autocomplete, or raw_id when there are many tags.",
                        to="blog.tag",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Comment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "author_name",
                    models.CharField(
                        help_text="search? no (not name/slug).", max_length=100
                    ),
                ),
                (
                    "body",
                    models.TextField(help_text="TextField: skipped by list_filter."),
                ),
                (
                    "created_at",
                    models.DateField(
                        help_text="DateField: date_hierarchy + list_filter."
                    ),
                ),
                (
                    "post",
                    models.ForeignKey(
                        help_text="FK to a large table: becomes raw_id_fields.",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="blog.post",
                    ),
                ),
            ],
        ),
    ]
