name: tox

on:
  push:
  pull_request:

jobs:
  setup:
    runs-on: ubuntu-latest
    timeout-minutes: 1
    outputs:
      tox-envs: ${{ steps.set-matrix.outputs.tox-envs }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: 'pip'
      - run: python -m pip install --upgrade tox
      - id: set-matrix
        run: |
          echo tox-envs=$(tox -l | grep py | jq -R -s -c 'split("\n") | map(select(length > 0))') >> $GITHUB_OUTPUT

  build:
    needs: setup
    runs-on: ubuntu-latest
    timeout-minutes: 10
    strategy:
      fail-fast: false
      matrix:
        tox-env: ${{ fromJson(needs.setup.outputs.tox-envs) }}

    steps:
      - run: |
          PY=${{ matrix.tox-env }}
          PY=${PY//-django*/}
          PY=${PY//py3/3.}
          echo "PY=$PY" >> $GITHUB_ENV
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ env.PY }}
          cache: 'pip'
      - run: python -m pip install --upgrade tox
      - run: tox --skip-missing-interpreters -e ${{ matrix.tox-env }}

  docs:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: 'pip'
      - run: python -m pip install --upgrade tox
      - run: tox --skip-missing-interpreters -e docs

  flake8:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: 'pip'
      - run: python -m pip install --upgrade tox
      - run: tox --skip-missing-interpreters -e flake8
