name: tox

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  setup:
    runs-on: ubuntu-latest
    timeout-minutes: 1
    outputs:
      tox_envs: ${{ steps.set-matrix.outputs.tox_envs }}
    steps:
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - uses: actions/checkout@v3
      - run: python -m pip install --upgrade tox
      - id: set-matrix
        run: |
          echo tox_envs=$(tox -l | jq -R -s -c 'split("\n") | map(select(length > 0))')

  build:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    strategy:
      matrix:
        python-version: ['3.10']
#        python-version: ['3.7', '3.8', '3.9', '3.10', '3.11']
        tox-env: ${{ fromJson(needs.setup.outputs.tox_envs) }}

    steps:
    - run: cat $GITHUB_OUTPUT
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    - run: python -m pip install --upgrade tox
    - run: tox -e ${{ matrix.tox-env }}
